CREATE SEQUENCE  IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE authors (
  author_id INTEGER NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_authors PRIMARY KEY (author_id)
);


CREATE SEQUENCE  IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;
CREATE TABLE books (
  id INTEGER NOT NULL,
   name VARCHAR(255),
   price INTEGER NOT NULL,
   author_id INTEGER NOT NULL,
   CONSTRAINT pk_books PRIMARY KEY (id)
);

ALTER TABLE books ADD CONSTRAINT FK_BOOKS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES authors (author_id);

